/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "gaggimate.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(GaggiMessage, GaggiMessage, AUTO)


PB_BIND(PingRequest, PingRequest, AUTO)


PB_BIND(OutputControlRequest, OutputControlRequest, AUTO)


PB_BIND(PidSettingsRequest, PidSettingsRequest, AUTO)


PB_BIND(PumpModelCoeffsRequest, PumpModelCoeffsRequest, AUTO)


PB_BIND(AutotuneRequest, AutotuneRequest, AUTO)


PB_BIND(PressureScaleRequest, PressureScaleRequest, AUTO)


PB_BIND(TareRequest, TareRequest, AUTO)


PB_BIND(LedControlRequest, LedControlRequest, AUTO)


PB_BIND(AltControlRequest, AltControlRequest, AUTO)


PB_BIND(ErrorResponse, ErrorResponse, AUTO)


PB_BIND(SensorDataResponse, SensorDataResponse, AUTO)


PB_BIND(BrewButtonResponse, BrewButtonResponse, AUTO)


PB_BIND(SteamButtonResponse, SteamButtonResponse, AUTO)


PB_BIND(AutotuneResultResponse, AutotuneResultResponse, AUTO)


PB_BIND(VolumetricMeasurementResponse, VolumetricMeasurementResponse, AUTO)


PB_BIND(TofMeasurementResponse, TofMeasurementResponse, AUTO)


PB_BIND(SystemInfoResponse, SystemInfoResponse, AUTO)





