/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_GAGGIMATE_PB_H_INCLUDED
#define PB_GAGGIMATE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _MessageType: uint8_t {
    MessageType_MSG_UNKNOWN = 0,
    MessageType_MSG_PING = 10,
    MessageType_MSG_OUTPUT_CONTROL = 11,
    MessageType_MSG_PID_SETTINGS = 12,
    MessageType_MSG_PUMP_MODEL = 13,
    MessageType_MSG_AUTOTUNE = 14,
    MessageType_MSG_PRESSURE_SCALE = 15,
    MessageType_MSG_TARE = 16,
    MessageType_MSG_LED_CONTROL = 17,
    MessageType_MSG_ALT_CONTROL = 18,
    MessageType_MSG_ERROR = 20,
    MessageType_MSG_SENSOR_DATA = 21,
    MessageType_MSG_BREW_BUTTON = 22,
    MessageType_MSG_STEAM_BUTTON = 23,
    MessageType_MSG_AUTOTUNE_RESULT = 24,
    MessageType_MSG_VOLUMETRIC = 25,
    MessageType_MSG_TOF = 26,
    MessageType_MSG_SYSTEM_INFO = 27
} MessageType;

/* Struct definitions */
typedef struct _PingRequest {
    char dummy_field;
} PingRequest;

typedef struct _OutputControlRequest {
    uint32_t mode;
    bool valve_open;
    float pump_setpoint;
    float boiler_setpoint;
    bool pressure_target;
    float pressure;
    float flow;
} OutputControlRequest;

typedef struct _PidSettingsRequest {
    float kp;
    float ki;
    float kd;
} PidSettingsRequest;

typedef struct _PumpModelCoeffsRequest {
    float a;
    float b;
    float c;
    float d;
} PumpModelCoeffsRequest;

typedef struct _AutotuneRequest {
    uint32_t test_time;
    uint32_t samples;
} AutotuneRequest;

typedef struct _PressureScaleRequest {
    float scale;
} PressureScaleRequest;

typedef struct _TareRequest {
    char dummy_field;
} TareRequest;

typedef struct _LedControlRequest {
    uint32_t channel;
    uint32_t brightness;
} LedControlRequest;

typedef struct _AltControlRequest {
    bool pin_state;
} AltControlRequest;

typedef struct _ErrorResponse {
    uint32_t error_code;
} ErrorResponse;

typedef struct _SensorDataResponse {
    float temperature;
    float pressure;
    float puck_flow;
    float pump_flow;
    float puck_resistance;
} SensorDataResponse;

typedef struct _BrewButtonResponse {
    bool button_state;
} BrewButtonResponse;

typedef struct _SteamButtonResponse {
    bool button_state;
} SteamButtonResponse;

typedef struct _AutotuneResultResponse {
    float kp;
    float ki;
    float kd;
} AutotuneResultResponse;

typedef struct _VolumetricMeasurementResponse {
    float volume;
} VolumetricMeasurementResponse;

typedef struct _TofMeasurementResponse {
    uint32_t distance;
} TofMeasurementResponse;

typedef struct _SystemInfoResponse {
    char info[128];
} SystemInfoResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _MessageType_MIN MessageType_MSG_UNKNOWN
#define _MessageType_MAX MessageType_MSG_SYSTEM_INFO
#define _MessageType_ARRAYSIZE ((MessageType)(MessageType_MSG_SYSTEM_INFO+1))



















/* Initializer values for message structs */
#define PingRequest_init_default                 {0}
#define OutputControlRequest_init_default        {0, 0, 0, 0, 0, 0, 0}
#define PidSettingsRequest_init_default          {0, 0, 0}
#define PumpModelCoeffsRequest_init_default      {0, 0, 0, 0}
#define AutotuneRequest_init_default             {0, 0}
#define PressureScaleRequest_init_default        {0}
#define TareRequest_init_default                 {0}
#define LedControlRequest_init_default           {0, 0}
#define AltControlRequest_init_default           {0}
#define ErrorResponse_init_default               {0}
#define SensorDataResponse_init_default          {0, 0, 0, 0, 0}
#define BrewButtonResponse_init_default          {0}
#define SteamButtonResponse_init_default         {0}
#define AutotuneResultResponse_init_default      {0, 0, 0}
#define VolumetricMeasurementResponse_init_default {0}
#define TofMeasurementResponse_init_default      {0}
#define SystemInfoResponse_init_default          {""}
#define PingRequest_init_zero                    {0}
#define OutputControlRequest_init_zero           {0, 0, 0, 0, 0, 0, 0}
#define PidSettingsRequest_init_zero             {0, 0, 0}
#define PumpModelCoeffsRequest_init_zero         {0, 0, 0, 0}
#define AutotuneRequest_init_zero                {0, 0}
#define PressureScaleRequest_init_zero           {0}
#define TareRequest_init_zero                    {0}
#define LedControlRequest_init_zero              {0, 0}
#define AltControlRequest_init_zero              {0}
#define ErrorResponse_init_zero                  {0}
#define SensorDataResponse_init_zero             {0, 0, 0, 0, 0}
#define BrewButtonResponse_init_zero             {0}
#define SteamButtonResponse_init_zero            {0}
#define AutotuneResultResponse_init_zero         {0, 0, 0}
#define VolumetricMeasurementResponse_init_zero  {0}
#define TofMeasurementResponse_init_zero         {0}
#define SystemInfoResponse_init_zero             {""}

/* Field tags (for use in manual encoding/decoding) */
#define OutputControlRequest_mode_tag            1
#define OutputControlRequest_valve_open_tag      2
#define OutputControlRequest_pump_setpoint_tag   3
#define OutputControlRequest_boiler_setpoint_tag 4
#define OutputControlRequest_pressure_target_tag 5
#define OutputControlRequest_pressure_tag        6
#define OutputControlRequest_flow_tag            7
#define PidSettingsRequest_kp_tag                1
#define PidSettingsRequest_ki_tag                2
#define PidSettingsRequest_kd_tag                3
#define PumpModelCoeffsRequest_a_tag             1
#define PumpModelCoeffsRequest_b_tag             2
#define PumpModelCoeffsRequest_c_tag             3
#define PumpModelCoeffsRequest_d_tag             4
#define AutotuneRequest_test_time_tag            1
#define AutotuneRequest_samples_tag              2
#define PressureScaleRequest_scale_tag           1
#define LedControlRequest_channel_tag            1
#define LedControlRequest_brightness_tag         2
#define AltControlRequest_pin_state_tag          1
#define ErrorResponse_error_code_tag             1
#define SensorDataResponse_temperature_tag       1
#define SensorDataResponse_pressure_tag          2
#define SensorDataResponse_puck_flow_tag         3
#define SensorDataResponse_pump_flow_tag         4
#define SensorDataResponse_puck_resistance_tag   5
#define BrewButtonResponse_button_state_tag      1
#define SteamButtonResponse_button_state_tag     1
#define AutotuneResultResponse_kp_tag            1
#define AutotuneResultResponse_ki_tag            2
#define AutotuneResultResponse_kd_tag            3
#define VolumetricMeasurementResponse_volume_tag 1
#define TofMeasurementResponse_distance_tag      1
#define SystemInfoResponse_info_tag              1

/* Struct field encoding specification for nanopb */
#define PingRequest_FIELDLIST(X, a) \

#define PingRequest_CALLBACK NULL
#define PingRequest_DEFAULT NULL

#define OutputControlRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   mode,              1) \
X(a, STATIC,   SINGULAR, BOOL,     valve_open,        2) \
X(a, STATIC,   SINGULAR, FLOAT,    pump_setpoint,     3) \
X(a, STATIC,   SINGULAR, FLOAT,    boiler_setpoint,   4) \
X(a, STATIC,   SINGULAR, BOOL,     pressure_target,   5) \
X(a, STATIC,   SINGULAR, FLOAT,    pressure,          6) \
X(a, STATIC,   SINGULAR, FLOAT,    flow,              7)
#define OutputControlRequest_CALLBACK NULL
#define OutputControlRequest_DEFAULT NULL

#define PidSettingsRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    kp,                1) \
X(a, STATIC,   SINGULAR, FLOAT,    ki,                2) \
X(a, STATIC,   SINGULAR, FLOAT,    kd,                3)
#define PidSettingsRequest_CALLBACK NULL
#define PidSettingsRequest_DEFAULT NULL

#define PumpModelCoeffsRequest_FIELDLIST(X, a_) \
X(a_, STATIC,   SINGULAR, FLOAT,    a,                 1) \
X(a_, STATIC,   SINGULAR, FLOAT,    b,                 2) \
X(a_, STATIC,   SINGULAR, FLOAT,    c,                 3) \
X(a_, STATIC,   SINGULAR, FLOAT,    d,                 4)
#define PumpModelCoeffsRequest_CALLBACK NULL
#define PumpModelCoeffsRequest_DEFAULT NULL

#define AutotuneRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   test_time,         1) \
X(a, STATIC,   SINGULAR, UINT32,   samples,           2)
#define AutotuneRequest_CALLBACK NULL
#define AutotuneRequest_DEFAULT NULL

#define PressureScaleRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    scale,             1)
#define PressureScaleRequest_CALLBACK NULL
#define PressureScaleRequest_DEFAULT NULL

#define TareRequest_FIELDLIST(X, a) \

#define TareRequest_CALLBACK NULL
#define TareRequest_DEFAULT NULL

#define LedControlRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   channel,           1) \
X(a, STATIC,   SINGULAR, UINT32,   brightness,        2)
#define LedControlRequest_CALLBACK NULL
#define LedControlRequest_DEFAULT NULL

#define AltControlRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     pin_state,         1)
#define AltControlRequest_CALLBACK NULL
#define AltControlRequest_DEFAULT NULL

#define ErrorResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   error_code,        1)
#define ErrorResponse_CALLBACK NULL
#define ErrorResponse_DEFAULT NULL

#define SensorDataResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       1) \
X(a, STATIC,   SINGULAR, FLOAT,    pressure,          2) \
X(a, STATIC,   SINGULAR, FLOAT,    puck_flow,         3) \
X(a, STATIC,   SINGULAR, FLOAT,    pump_flow,         4) \
X(a, STATIC,   SINGULAR, FLOAT,    puck_resistance,   5)
#define SensorDataResponse_CALLBACK NULL
#define SensorDataResponse_DEFAULT NULL

#define BrewButtonResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     button_state,      1)
#define BrewButtonResponse_CALLBACK NULL
#define BrewButtonResponse_DEFAULT NULL

#define SteamButtonResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     button_state,      1)
#define SteamButtonResponse_CALLBACK NULL
#define SteamButtonResponse_DEFAULT NULL

#define AutotuneResultResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    kp,                1) \
X(a, STATIC,   SINGULAR, FLOAT,    ki,                2) \
X(a, STATIC,   SINGULAR, FLOAT,    kd,                3)
#define AutotuneResultResponse_CALLBACK NULL
#define AutotuneResultResponse_DEFAULT NULL

#define VolumetricMeasurementResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    volume,            1)
#define VolumetricMeasurementResponse_CALLBACK NULL
#define VolumetricMeasurementResponse_DEFAULT NULL

#define TofMeasurementResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   distance,          1)
#define TofMeasurementResponse_CALLBACK NULL
#define TofMeasurementResponse_DEFAULT NULL

#define SystemInfoResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   info,              1)
#define SystemInfoResponse_CALLBACK NULL
#define SystemInfoResponse_DEFAULT NULL

extern const pb_msgdesc_t PingRequest_msg;
extern const pb_msgdesc_t OutputControlRequest_msg;
extern const pb_msgdesc_t PidSettingsRequest_msg;
extern const pb_msgdesc_t PumpModelCoeffsRequest_msg;
extern const pb_msgdesc_t AutotuneRequest_msg;
extern const pb_msgdesc_t PressureScaleRequest_msg;
extern const pb_msgdesc_t TareRequest_msg;
extern const pb_msgdesc_t LedControlRequest_msg;
extern const pb_msgdesc_t AltControlRequest_msg;
extern const pb_msgdesc_t ErrorResponse_msg;
extern const pb_msgdesc_t SensorDataResponse_msg;
extern const pb_msgdesc_t BrewButtonResponse_msg;
extern const pb_msgdesc_t SteamButtonResponse_msg;
extern const pb_msgdesc_t AutotuneResultResponse_msg;
extern const pb_msgdesc_t VolumetricMeasurementResponse_msg;
extern const pb_msgdesc_t TofMeasurementResponse_msg;
extern const pb_msgdesc_t SystemInfoResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define PingRequest_fields &PingRequest_msg
#define OutputControlRequest_fields &OutputControlRequest_msg
#define PidSettingsRequest_fields &PidSettingsRequest_msg
#define PumpModelCoeffsRequest_fields &PumpModelCoeffsRequest_msg
#define AutotuneRequest_fields &AutotuneRequest_msg
#define PressureScaleRequest_fields &PressureScaleRequest_msg
#define TareRequest_fields &TareRequest_msg
#define LedControlRequest_fields &LedControlRequest_msg
#define AltControlRequest_fields &AltControlRequest_msg
#define ErrorResponse_fields &ErrorResponse_msg
#define SensorDataResponse_fields &SensorDataResponse_msg
#define BrewButtonResponse_fields &BrewButtonResponse_msg
#define SteamButtonResponse_fields &SteamButtonResponse_msg
#define AutotuneResultResponse_fields &AutotuneResultResponse_msg
#define VolumetricMeasurementResponse_fields &VolumetricMeasurementResponse_msg
#define TofMeasurementResponse_fields &TofMeasurementResponse_msg
#define SystemInfoResponse_fields &SystemInfoResponse_msg

/* Maximum encoded size of messages (where known) */
#define AltControlRequest_size                   2
#define AutotuneRequest_size                     12
#define AutotuneResultResponse_size              15
#define BrewButtonResponse_size                  2
#define ErrorResponse_size                       6
#define GAGGIMATE_PB_H_MAX_SIZE                  SystemInfoResponse_size
#define LedControlRequest_size                   12
#define OutputControlRequest_size                30
#define PidSettingsRequest_size                  15
#define PingRequest_size                         0
#define PressureScaleRequest_size                5
#define PumpModelCoeffsRequest_size              20
#define SensorDataResponse_size                  25
#define SteamButtonResponse_size                 2
#define SystemInfoResponse_size                  130
#define TareRequest_size                         0
#define TofMeasurementResponse_size              6
#define VolumetricMeasurementResponse_size       5

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
