// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: GaggiMate

#ifndef _GAGGIMATE_UI_H
#define _GAGGIMATE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////

#include "ui_InitScreen.h"
#include "ui_ProfileScreen.h"
#include "ui_MenuScreen.h"
#include "ui_BrewScreen.h"
#include "ui_SimpleProcessScreen.h"
#include "ui_StandbyScreen.h"
#include "ui_StatusScreen.h"
#include "ui_GrindScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_logo_png);    // assets/logo.png
LV_IMG_DECLARE(ui_img_untitled_png);    // assets/Untitled.png
LV_IMG_DECLARE(ui_img_489054950);    // assets/gauge-fill.png
LV_IMG_DECLARE(ui_img_340686386);    // assets/indicator-small.png
LV_IMG_DECLARE(ui_img_1455708189);    // assets/pressure-filled.png
LV_IMG_DECLARE(ui_img_1951499226);    // assets/thermometer-half-40x40.png
LV_IMG_DECLARE(ui_img_1220767159);    // assets/tachometer-fast-40x40.png
LV_IMG_DECLARE(ui_img_295763949);    // assets/angle-up-40x40.png
LV_IMG_DECLARE(ui_img_360122106);    // assets/clock-40x40.png
LV_IMG_DECLARE(ui_img_98036921);    // assets/angle-left-40x40.png
LV_IMG_DECLARE(ui_img_944513416);    // assets/angle-right-40x40.png
LV_IMG_DECLARE(ui_img_631115820);    // assets/check-40x40.png
LV_IMG_DECLARE(ui_img_2044104741);    // assets/power-40x40.png
LV_IMG_DECLARE(ui_img_979979123);    // assets/mug-hot-alt-80x80.png
LV_IMG_DECLARE(ui_img_783005998);    // assets/wind-80x80.png
LV_IMG_DECLARE(ui_img_545340440);    // assets/raindrops-80x80.png
LV_IMG_DECLARE(ui_img_363557387);    // assets/coffee-bean-80x80.png
LV_IMG_DECLARE(ui_img_445946954);    // assets/play-40x40.png
LV_IMG_DECLARE(ui_img_1424216268);    // assets/equality-40x40.png
LV_IMG_DECLARE(ui_img_207915003);    // assets/refresh-40x40.png
LV_IMG_DECLARE(ui_img_834125362);    // assets/minus-small-40x40.png
LV_IMG_DECLARE(ui_img_390988422);    // assets/plus-small-40x40.png
LV_IMG_DECLARE(ui_img_364513079);    // assets/wifi-20x20.png
LV_IMG_DECLARE(ui_img_1091371356);    // assets/bluetooth-alt-20x20.png
LV_IMG_DECLARE(ui_img_1765671371);    // assets/refresh-20x20.png
LV_IMG_DECLARE(ui_img_1732953241);    // assets/tap-60x60.png
LV_IMG_DECLARE(ui_img_1456692430);    // assets/pause-40x40.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
