// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: GaggiMate

#include "../../../main.h"
#include "../../../plugins/BLEScalePlugin.h"
#include "ui.h"
#include <Arduino.h>

// Flag to track if volumetric hold was triggered
static bool volumetricHoldTriggered = false;

void onBrewTempLower(lv_event_t *e) {
    controller.getUI()->markProfileDirty();
    controller.lowerTemp();
}

void onBrewTempRaise(lv_event_t *e) {
    controller.getUI()->markProfileDirty();
    controller.raiseTemp();
}

void onWakeup(lv_event_t *e) {
    if (controller.isUpdating() || controller.isErrorState() || controller.isAutotuning() ||
        !controller.getClientController()->isConnected()) {
        return;
    }
    controller.getUI()->changeScreen(&ui_BrewScreen, &ui_BrewScreen_screen_init);
    controller.deactivate();
    controller.setMode(MODE_BREW);
}

void onLoadStarted(lv_event_t *e) {}

void onStandby(lv_event_t *e) { controller.activateStandby(); }

void onProfileSave(lv_event_t *e) {
    controller.onProfileSave();
    controller.getUI()->markProfileClean();
    controller.getUI()->changeBrewScreenMode(BrewScreenState::Brew);
}

void onBrewScreenLoad(lv_event_t * e)
{
	// Your code here
}

void onMenuClick(lv_event_t * e)
{
	// Your code here
}

void onStatusScreenLoad(lv_event_t * e)
{
	// Your code here
}
