// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void onStandby(lv_event_t * e);
void onBrewScreenLoad(lv_event_t * e);
void onMenuClick(lv_event_t * e);
void onProfileSave(lv_event_t * e);
void onBrewTempLower(lv_event_t * e);
void onBrewTempRaise(lv_event_t * e);
void onStatusScreenLoad(lv_event_t * e);
void onWakeup(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
