// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: GaggiMate

#include "ui.h"

lv_obj_t * uic_ProfileScreen_dials_weightText;
lv_obj_t * uic_ProfileScreen_dials_tempText;
lv_obj_t * uic_ProfileScreen_dials_pressureText;
lv_obj_t * uic_ProfileScreen_dials_pressureTarget;
lv_obj_t * uic_ProfileScreen_dials_pressureGauge;
lv_obj_t * uic_ProfileScreen_dials_tempTarget;
lv_obj_t * uic_ProfileScreen_dials_tempGauge;
lv_obj_t * ui_ProfileScreen = NULL;
lv_obj_t * ui_ProfileScreen_dials = NULL;
lv_obj_t * ui_ProfileScreen_ImgButton1 = NULL;
lv_obj_t * ui_ProfileScreen_contentPanel = NULL;
lv_obj_t * ui_ProfileScreen_mainLabel = NULL;
lv_obj_t * ui_ProfileScreen_profileName = NULL;
lv_obj_t * ui_ProfileScreen_tempIcon = NULL;
lv_obj_t * ui_ProfileScreen_targetIcon = NULL;
lv_obj_t * ui_ProfileScreen_targetTemp2 = NULL;
lv_obj_t * ui_ProfileScreen_targetDuration2 = NULL;
lv_obj_t * ui_ProfileScreen_extendedContent = NULL;
lv_obj_t * ui_ProfileScreen_Chart1 = NULL;
lv_obj_t * ui_ProfileScreen_Chart1_Xaxis = NULL;
lv_obj_t * ui_ProfileScreen_Chart1_Yaxis1 = NULL;
lv_obj_t * ui_ProfileScreen_Chart1_Yaxis2 = NULL;
lv_obj_t * ui_ProfileScreen_simpleContent = NULL;
lv_obj_t * ui_ProfileScreen_phasesLabel = NULL;
lv_obj_t * ui_ProfileScreen_stepsLabel = NULL;
lv_obj_t * ui_ProfileScreen_previousProfileBtn = NULL;
lv_obj_t * ui_ProfileScreen_nextProfileBtn = NULL;
lv_obj_t * ui_ProfileScreen_chooseButton = NULL;
// event funtions
void ui_event_ProfileScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_active());
        onMenuClick(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        onNextProfile(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        onPreviousProfile(e);
    }
}

void ui_event_ProfileScreen_ImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        onMenuClick(e);
    }
}

void ui_event_ProfileScreen_previousProfileBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        onPreviousProfile(e);
    }
}

void ui_event_ProfileScreen_nextProfileBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        onNextProfile(e);
    }
}

void ui_event_ProfileScreen_chooseButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        onProfileLoad(e);
    }
}

// build funtions

void ui_ProfileScreen_screen_init(void)
{
    ui_ProfileScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ProfileScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_ProfileScreen, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, &ui_ProfileScreen);
    ui_object_set_themeable_style_property(ui_ProfileScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(ui_ProfileScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Dark);

    ui_ProfileScreen_dials = ui_dials_create(ui_ProfileScreen);
    lv_obj_set_x(ui_ProfileScreen_dials, 0);
    lv_obj_set_y(ui_ProfileScreen_dials, 0);

    ui_ProfileScreen_ImgButton1 = lv_imagebutton_create(ui_ProfileScreen);
    lv_imagebutton_set_src(ui_ProfileScreen_ImgButton1, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_295763949, NULL);
    lv_obj_set_width(ui_ProfileScreen_ImgButton1, 40);
    lv_obj_set_height(ui_ProfileScreen_ImgButton1, 40);
    lv_obj_set_x(ui_ProfileScreen_ImgButton1, 0);
    lv_obj_set_y(ui_ProfileScreen_ImgButton1, 210);
    lv_obj_set_align(ui_ProfileScreen_ImgButton1, LV_ALIGN_CENTER);
    lv_obj_set_style_outline_color(ui_ProfileScreen_ImgButton1, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ProfileScreen_ImgButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ProfileScreen_ImgButton1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ProfileScreen_ImgButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor(ui_ProfileScreen_ImgButton1, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_ProfileScreen_ImgButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProfileScreen_contentPanel = lv_obj_create(ui_ProfileScreen);
    lv_obj_set_width(ui_ProfileScreen_contentPanel, 360);
    lv_obj_set_height(ui_ProfileScreen_contentPanel, 360);
    lv_obj_set_align(ui_ProfileScreen_contentPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ProfileScreen_contentPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ProfileScreen_contentPanel, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ProfileScreen_contentPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProfileScreen_contentPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ProfileScreen_contentPanel, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_ProfileScreen_contentPanel, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_border_width(ui_ProfileScreen_contentPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProfileScreen_mainLabel = lv_label_create(ui_ProfileScreen_contentPanel);
    lv_obj_set_width(ui_ProfileScreen_mainLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ProfileScreen_mainLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ProfileScreen_mainLabel, 0);
    lv_obj_set_y(ui_ProfileScreen_mainLabel, -140);
    lv_obj_set_align(ui_ProfileScreen_mainLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ProfileScreen_mainLabel, "Select profile");
    ui_object_set_themeable_style_property(ui_ProfileScreen_mainLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_ProfileScreen_mainLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_font(ui_ProfileScreen_mainLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProfileScreen_profileName = lv_label_create(ui_ProfileScreen_contentPanel);
    lv_obj_set_width(ui_ProfileScreen_profileName, 315);
    lv_obj_set_height(ui_ProfileScreen_profileName, 30);
    lv_obj_set_x(ui_ProfileScreen_profileName, 0);
    lv_obj_set_y(ui_ProfileScreen_profileName, -90);
    lv_obj_set_align(ui_ProfileScreen_profileName, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_ProfileScreen_profileName, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_ProfileScreen_profileName, "Cremina Lever");
    ui_object_set_themeable_style_property(ui_ProfileScreen_profileName, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_ProfileScreen_profileName, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_align(ui_ProfileScreen_profileName, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProfileScreen_profileName, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProfileScreen_tempIcon = lv_image_create(ui_ProfileScreen_contentPanel);
    lv_image_set_src(ui_ProfileScreen_tempIcon, &ui_img_1951499226);
    lv_obj_set_width(ui_ProfileScreen_tempIcon, 40);
    lv_obj_set_height(ui_ProfileScreen_tempIcon, 40);
    lv_obj_set_x(ui_ProfileScreen_tempIcon, -100);
    lv_obj_set_y(ui_ProfileScreen_tempIcon, -50);
    lv_obj_set_align(ui_ProfileScreen_tempIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ProfileScreen_tempIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_ProfileScreen_tempIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_ProfileScreen_tempIcon, 150);
    lv_image_set_inner_align(ui_ProfileScreen_tempIcon, LV_IMAGE_ALIGN_TILE);
    ui_object_set_themeable_style_property(ui_ProfileScreen_tempIcon, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_ProfileScreen_tempIcon, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

    ui_ProfileScreen_targetIcon = lv_image_create(ui_ProfileScreen_contentPanel);
    lv_image_set_src(ui_ProfileScreen_targetIcon, &ui_img_360122106);
    lv_obj_set_width(ui_ProfileScreen_targetIcon, 40);
    lv_obj_set_height(ui_ProfileScreen_targetIcon, 40);
    lv_obj_set_x(ui_ProfileScreen_targetIcon, 0);
    lv_obj_set_y(ui_ProfileScreen_targetIcon, -50);
    lv_obj_set_align(ui_ProfileScreen_targetIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ProfileScreen_targetIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_ProfileScreen_targetIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_ProfileScreen_targetIcon, 150);
    lv_image_set_inner_align(ui_ProfileScreen_targetIcon, LV_IMAGE_ALIGN_TILE);
    ui_object_set_themeable_style_property(ui_ProfileScreen_targetIcon, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_ProfileScreen_targetIcon, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

    ui_ProfileScreen_targetTemp2 = lv_label_create(ui_ProfileScreen_contentPanel);
    lv_obj_set_width(ui_ProfileScreen_targetTemp2, 60);
    lv_obj_set_height(ui_ProfileScreen_targetTemp2, 20);
    lv_obj_set_x(ui_ProfileScreen_targetTemp2, -50);
    lv_obj_set_y(ui_ProfileScreen_targetTemp2, -50);
    lv_obj_set_align(ui_ProfileScreen_targetTemp2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ProfileScreen_targetTemp2, "80°C");
    ui_object_set_themeable_style_property(ui_ProfileScreen_targetTemp2, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_ProfileScreen_targetTemp2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_align(ui_ProfileScreen_targetTemp2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProfileScreen_targetTemp2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProfileScreen_targetDuration2 = lv_label_create(ui_ProfileScreen_contentPanel);
    lv_obj_set_width(ui_ProfileScreen_targetDuration2, 60);
    lv_obj_set_height(ui_ProfileScreen_targetDuration2, 20);
    lv_obj_set_x(ui_ProfileScreen_targetDuration2, 50);
    lv_obj_set_y(ui_ProfileScreen_targetDuration2, -50);
    lv_obj_set_align(ui_ProfileScreen_targetDuration2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ProfileScreen_targetDuration2, "0:30");
    ui_object_set_themeable_style_property(ui_ProfileScreen_targetDuration2, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_ProfileScreen_targetDuration2, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_align(ui_ProfileScreen_targetDuration2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProfileScreen_targetDuration2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProfileScreen_extendedContent = lv_obj_create(ui_ProfileScreen_contentPanel);
    lv_obj_remove_style_all(ui_ProfileScreen_extendedContent);
    lv_obj_set_width(ui_ProfileScreen_extendedContent, 250);
    lv_obj_set_height(ui_ProfileScreen_extendedContent, 130);
    lv_obj_set_x(ui_ProfileScreen_extendedContent, 0);
    lv_obj_set_y(ui_ProfileScreen_extendedContent, 30);
    lv_obj_set_align(ui_ProfileScreen_extendedContent, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ProfileScreen_extendedContent, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_ProfileScreen_extendedContent, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ProfileScreen_Chart1 = lv_chart_create(ui_ProfileScreen_extendedContent);
    lv_obj_set_width(ui_ProfileScreen_Chart1, 240);
    lv_obj_set_height(ui_ProfileScreen_Chart1, 120);
    lv_obj_set_align(ui_ProfileScreen_Chart1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ProfileScreen_Chart1,
                    LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_ProfileScreen_Chart1, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_ProfileScreen_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_ProfileScreen_Chart1, 31);
    lv_chart_set_range(ui_ProfileScreen_Chart1, LV_CHART_AXIS_PRIMARY_Y, 0, 15);
    lv_chart_set_range(ui_ProfileScreen_Chart1, LV_CHART_AXIS_SECONDARY_Y, 0, 5);
    lv_chart_set_div_line_count(ui_ProfileScreen_Chart1, 0, 0);
    ui_object_set_themeable_style_property(ui_ProfileScreen_Chart1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(ui_ProfileScreen_Chart1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Dark);
    ui_object_set_themeable_style_property(ui_ProfileScreen_Chart1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(ui_ProfileScreen_Chart1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Dark);

    ui_ProfileScreen_Chart1_Xaxis = lv_scale_create(ui_ProfileScreen_Chart1);
    lv_scale_set_mode(ui_ProfileScreen_Chart1_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_ProfileScreen_Chart1_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_ProfileScreen_Chart1_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_ProfileScreen_Chart1_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_ProfileScreen_Chart1,
                                                                                 LV_PART_MAIN) + lv_obj_get_style_border_width(ui_ProfileScreen_Chart1, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_ProfileScreen_Chart1_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_ProfileScreen_Chart1_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_ProfileScreen_Chart1_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_ProfileScreen_Chart1_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_ProfileScreen_Chart1_Xaxis, 5, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_ProfileScreen_Chart1_Xaxis, 0, 5 > 0 ? 5 - 1 : 0);
    lv_scale_set_total_tick_count(ui_ProfileScreen_Chart1_Xaxis, (5 > 0 ? 5 - 1 : 0) * 5 + 1);
    lv_scale_set_major_tick_every(ui_ProfileScreen_Chart1_Xaxis, 5 >= 1 ? 5 : 1);
    lv_scale_set_label_show(ui_ProfileScreen_Chart1_Xaxis, false);
    ui_ProfileScreen_Chart1_Yaxis1 = lv_scale_create(ui_ProfileScreen_Chart1);
    lv_scale_set_mode(ui_ProfileScreen_Chart1_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_ProfileScreen_Chart1_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_ProfileScreen_Chart1_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_ProfileScreen_Chart1_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_ProfileScreen_Chart1,
                                                                                 LV_PART_MAIN) - lv_obj_get_style_border_width(ui_ProfileScreen_Chart1, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_ProfileScreen_Chart1_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_ProfileScreen_Chart1_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_ProfileScreen_Chart1_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_ProfileScreen_Chart1_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_ProfileScreen_Chart1_Yaxis1, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_ProfileScreen_Chart1_Yaxis1,  0, 15);
    lv_scale_set_total_tick_count(ui_ProfileScreen_Chart1_Yaxis1, (0 > 0 ? 0 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_ProfileScreen_Chart1_Yaxis1, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_ProfileScreen_Chart1_Yaxis1, false);
    ui_ProfileScreen_Chart1_Yaxis2 = lv_scale_create(ui_ProfileScreen_Chart1);
    lv_scale_set_mode(ui_ProfileScreen_Chart1_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_ProfileScreen_Chart1_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_ProfileScreen_Chart1_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_ProfileScreen_Chart1_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_ProfileScreen_Chart1,
                                                                                 LV_PART_MAIN) + lv_obj_get_style_border_width(ui_ProfileScreen_Chart1, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_ProfileScreen_Chart1_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_ProfileScreen_Chart1_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_ProfileScreen_Chart1_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_ProfileScreen_Chart1_Yaxis2, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_ProfileScreen_Chart1_Yaxis2, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_ProfileScreen_Chart1_Yaxis2,  0, 5);
    lv_scale_set_total_tick_count(ui_ProfileScreen_Chart1_Yaxis2, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_ProfileScreen_Chart1_Yaxis2, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_ProfileScreen_Chart1_Yaxis2, false);
    lv_chart_series_t * ui_ProfileScreen_Chart1_series_1 = lv_chart_add_series(ui_ProfileScreen_Chart1,
                                                                               lv_color_hex(0x2BA1F1), LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_ProfileScreen_Chart1_series_1_array[] = { 4, 4, 4, 1, 1, 1, 1, 1, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8 };
    lv_chart_set_ext_y_array(ui_ProfileScreen_Chart1, ui_ProfileScreen_Chart1_series_1,
                             ui_ProfileScreen_Chart1_series_1_array);
    lv_chart_series_t * ui_ProfileScreen_Chart1_series_2 = lv_chart_add_series(ui_ProfileScreen_Chart1,
                                                                               lv_color_hex(0x00BD58), LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_ProfileScreen_Chart1_series_2_array[] = { 2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 };
    lv_chart_set_ext_y_array(ui_ProfileScreen_Chart1, ui_ProfileScreen_Chart1_series_2,
                             ui_ProfileScreen_Chart1_series_2_array);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_ProfileScreen_Chart1, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_ProfileScreen_Chart1, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_ProfileScreen_simpleContent = lv_obj_create(ui_ProfileScreen_contentPanel);
    lv_obj_remove_style_all(ui_ProfileScreen_simpleContent);
    lv_obj_set_width(ui_ProfileScreen_simpleContent, 250);
    lv_obj_set_height(ui_ProfileScreen_simpleContent, 130);
    lv_obj_set_x(ui_ProfileScreen_simpleContent, 0);
    lv_obj_set_y(ui_ProfileScreen_simpleContent, 30);
    lv_obj_set_align(ui_ProfileScreen_simpleContent, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ProfileScreen_simpleContent, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ProfileScreen_simpleContent, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_remove_flag(ui_ProfileScreen_simpleContent, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ProfileScreen_phasesLabel = lv_label_create(ui_ProfileScreen_simpleContent);
    lv_obj_set_width(ui_ProfileScreen_phasesLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ProfileScreen_phasesLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ProfileScreen_phasesLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ProfileScreen_phasesLabel, "2 Phases");
    ui_object_set_themeable_style_property(ui_ProfileScreen_phasesLabel, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_ProfileScreen_phasesLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_font(ui_ProfileScreen_phasesLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProfileScreen_stepsLabel = lv_label_create(ui_ProfileScreen_simpleContent);
    lv_obj_set_width(ui_ProfileScreen_stepsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ProfileScreen_stepsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ProfileScreen_stepsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ProfileScreen_stepsLabel, "3 Steps");
    ui_object_set_themeable_style_property(ui_ProfileScreen_stepsLabel, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_ProfileScreen_stepsLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_font(ui_ProfileScreen_stepsLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProfileScreen_previousProfileBtn = lv_imagebutton_create(ui_ProfileScreen_contentPanel);
    lv_imagebutton_set_src(ui_ProfileScreen_previousProfileBtn, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_98036921,
                           NULL);
    lv_obj_set_width(ui_ProfileScreen_previousProfileBtn, 40);
    lv_obj_set_height(ui_ProfileScreen_previousProfileBtn, 40);
    lv_obj_set_x(ui_ProfileScreen_previousProfileBtn, -150);
    lv_obj_set_y(ui_ProfileScreen_previousProfileBtn, 0);
    lv_obj_set_align(ui_ProfileScreen_previousProfileBtn, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_ProfileScreen_previousProfileBtn, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_SemiDark);
    ui_object_set_themeable_style_property(ui_ProfileScreen_previousProfileBtn, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_SemiDark);

    ui_ProfileScreen_nextProfileBtn = lv_imagebutton_create(ui_ProfileScreen_contentPanel);
    lv_imagebutton_set_src(ui_ProfileScreen_nextProfileBtn, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_944513416, NULL);
    lv_obj_set_width(ui_ProfileScreen_nextProfileBtn, 40);
    lv_obj_set_height(ui_ProfileScreen_nextProfileBtn, 40);
    lv_obj_set_x(ui_ProfileScreen_nextProfileBtn, 150);
    lv_obj_set_y(ui_ProfileScreen_nextProfileBtn, 0);
    lv_obj_set_align(ui_ProfileScreen_nextProfileBtn, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_ProfileScreen_nextProfileBtn, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_ProfileScreen_nextProfileBtn, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

    ui_ProfileScreen_chooseButton = lv_imagebutton_create(ui_ProfileScreen_contentPanel);
    lv_imagebutton_set_src(ui_ProfileScreen_chooseButton, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_631115820, NULL);
    lv_obj_set_width(ui_ProfileScreen_chooseButton, 40);
    lv_obj_set_height(ui_ProfileScreen_chooseButton, 40);
    lv_obj_set_x(ui_ProfileScreen_chooseButton, 0);
    lv_obj_set_y(ui_ProfileScreen_chooseButton, 130);
    lv_obj_set_align(ui_ProfileScreen_chooseButton, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_ProfileScreen_chooseButton, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMAGE_RECOLOR, _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_ProfileScreen_chooseButton, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMAGE_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

    lv_obj_add_event_cb(ui_ProfileScreen_ImgButton1, ui_event_ProfileScreen_ImgButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ProfileScreen_previousProfileBtn, ui_event_ProfileScreen_previousProfileBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ProfileScreen_nextProfileBtn, ui_event_ProfileScreen_nextProfileBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ProfileScreen_chooseButton, ui_event_ProfileScreen_chooseButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ProfileScreen, ui_event_ProfileScreen, LV_EVENT_ALL, NULL);
    uic_ProfileScreen_dials_tempGauge = ui_comp_get_child(ui_ProfileScreen_dials, UI_COMP_DIALS_TEMPGAUGE);
    uic_ProfileScreen_dials_tempTarget = ui_comp_get_child(ui_ProfileScreen_dials, UI_COMP_DIALS_TEMPTARGET);
    uic_ProfileScreen_dials_pressureGauge = ui_comp_get_child(ui_ProfileScreen_dials, UI_COMP_DIALS_PRESSUREGAUGE);
    uic_ProfileScreen_dials_pressureTarget = ui_comp_get_child(ui_ProfileScreen_dials, UI_COMP_DIALS_PRESSURETARGET);
    uic_ProfileScreen_dials_pressureText = ui_comp_get_child(ui_ProfileScreen_dials, UI_COMP_DIALS_PRESSURETEXT);
    uic_ProfileScreen_dials_tempText = ui_comp_get_child(ui_ProfileScreen_dials, UI_COMP_DIALS_TEMPTEXT);
    uic_ProfileScreen_dials_weightText = ui_comp_get_child(ui_ProfileScreen_dials, UI_COMP_DIALS_WEIGHTTEXT);

}

void ui_ProfileScreen_screen_destroy(void)
{
    if(ui_ProfileScreen) lv_obj_del(ui_ProfileScreen);

    // NULL screen variables
    ui_ProfileScreen = NULL;
    ui_ProfileScreen_dials = NULL;
    uic_ProfileScreen_dials_tempGauge = NULL;
    uic_ProfileScreen_dials_tempTarget = NULL;
    uic_ProfileScreen_dials_pressureGauge = NULL;
    uic_ProfileScreen_dials_pressureTarget = NULL;
    uic_ProfileScreen_dials_pressureText = NULL;
    uic_ProfileScreen_dials_tempText = NULL;
    uic_ProfileScreen_dials_weightText = NULL;
    ui_ProfileScreen_ImgButton1 = NULL;
    ui_ProfileScreen_contentPanel = NULL;
    ui_ProfileScreen_mainLabel = NULL;
    ui_ProfileScreen_profileName = NULL;
    ui_ProfileScreen_tempIcon = NULL;
    ui_ProfileScreen_targetIcon = NULL;
    ui_ProfileScreen_targetTemp2 = NULL;
    ui_ProfileScreen_targetDuration2 = NULL;
    ui_ProfileScreen_extendedContent = NULL;
    ui_ProfileScreen_Chart1 = NULL;
    ui_ProfileScreen_simpleContent = NULL;
    ui_ProfileScreen_phasesLabel = NULL;
    ui_ProfileScreen_stepsLabel = NULL;
    ui_ProfileScreen_previousProfileBtn = NULL;
    ui_ProfileScreen_nextProfileBtn = NULL;
    ui_ProfileScreen_chooseButton = NULL;

}
