// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: GaggiMate

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_NICEWHITE 0
#define UI_THEME_COLOR_DARK 1
#define UI_THEME_COLOR_SEMIDARK 2
#define UI_THEME_COLOR_PROGRESS 3
#define UI_THEME_COLOR_HEATING 4

#define UI_THEME_DEFAULT 0

#define UI_THEME_LIGHT 1
#define UI_THEME_DARK_AMOLED 2

#define NUM_THEMES 3

extern const ui_theme_variable_t _ui_theme_color_NiceWhite[NUM_THEMES];
extern const ui_theme_variable_t _ui_theme_alpha_NiceWhite[NUM_THEMES];

extern const ui_theme_variable_t _ui_theme_color_Dark[NUM_THEMES];
extern const ui_theme_variable_t _ui_theme_alpha_Dark[NUM_THEMES];

extern const ui_theme_variable_t _ui_theme_color_SemiDark[NUM_THEMES];
extern const ui_theme_variable_t _ui_theme_alpha_SemiDark[NUM_THEMES];

extern const ui_theme_variable_t _ui_theme_color_Progress[NUM_THEMES];
extern const ui_theme_variable_t _ui_theme_alpha_Progress[NUM_THEMES];

extern const ui_theme_variable_t _ui_theme_color_Heating[NUM_THEMES];
extern const ui_theme_variable_t _ui_theme_alpha_Heating[NUM_THEMES];

extern const uint32_t *ui_theme_colors[NUM_THEMES];
extern const uint8_t *ui_theme_alphas[NUM_THEMES];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
