// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: GaggiMate

#include "ui.h"

void onLoadStarted(lv_event_t * e)
{
	// Your code here
}

void onMenuClick(lv_event_t * e)
{
	// Your code here
}

void onNextProfile(lv_event_t * e)
{
	// Your code here
}

void onPreviousProfile(lv_event_t * e)
{
	// Your code here
}

void onProfileScreenLoad(lv_event_t * e)
{
	// Your code here
}

void onProfileLoad(lv_event_t * e)
{
	// Your code here
}

void onMenuScreenLoad(lv_event_t * e)
{
	// Your code here
}

void onStandby(lv_event_t * e)
{
	// Your code here
}

void onBrewScreen(lv_event_t * e)
{
	// Your code here
}

void onSteamScreen(lv_event_t * e)
{
	// Your code here
}

void onWaterScreen(lv_event_t * e)
{
	// Your code here
}

void onGrindScreen(lv_event_t * e)
{
	// Your code here
}

void onBrewScreenLoad(lv_event_t * e)
{
	// Your code here
}

void onBrewStart(lv_event_t * e)
{
	// Your code here
}

void onFlush(lv_event_t * e)
{
	// Your code here
}

void onVolumetricClick(lv_event_t * e)
{
	// Your code here
}

void onVolumetricHold(lv_event_t * e)
{
	// Your code here
}

void onProfileSettings(lv_event_t * e)
{
	// Your code here
}

void onProfileSelect(lv_event_t * e)
{
	// Your code here
}

void onBrewTempLower(lv_event_t * e)
{
	// Your code here
}

void onBrewTempRaise(lv_event_t * e)
{
	// Your code here
}

void onBrewTimeRaise(lv_event_t * e)
{
	// Your code here
}

void onBrewTimeLower(lv_event_t * e)
{
	// Your code here
}

void onProfileSave(lv_event_t * e)
{
	// Your code here
}

void onProfileAccept(lv_event_t * e)
{
	// Your code here
}

void onProfileSaveAsNew(lv_event_t * e)
{
	// Your code here
}

void onWakeup(lv_event_t * e)
{
	// Your code here
}

void onSimpleProcessScreenLoad(lv_event_t * e)
{
	// Your code here
}

void onSimpleProcessToggle(lv_event_t * e)
{
	// Your code here
}

void onSteamTempLower(lv_event_t * e)
{
	// Your code here
}

void onSteamTempRaise(lv_event_t * e)
{
	// Your code here
}

void onStatusScreenLoad(lv_event_t * e)
{
	// Your code here
}

void onBrewCancel(lv_event_t * e)
{
	// Your code here
}

void onGrindScreenLoad(lv_event_t * e)
{
	// Your code here
}

void onGrindToggle(lv_event_t * e)
{
	// Your code here
}

void onGrindTimeRaise(lv_event_t * e)
{
	// Your code here
}

void onGrindTimeLower(lv_event_t * e)
{
	// Your code here
}
