#ifndef EEZ_LVGL_UI_VARS_H
#define EEZ_LVGL_UI_VARS_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// enum declarations

// Flow global variables

enum FlowGlobalVariables {
    FLOW_GLOBAL_VARIABLE_BOILER_TEMP_TARGET = 0,
    FLOW_GLOBAL_VARIABLE_BOILER_TEMP_CURRENT = 1,
    FLOW_GLOBAL_VARIABLE_BOILER_PRESSURE_TARGET = 2,
    FLOW_GLOBAL_VARIABLE_BOILER_PRESSURE_CURRENT = 3,
    FLOW_GLOBAL_VARIABLE_BOILER_PRESSURE_MAX = 4,
    FLOW_GLOBAL_VARIABLE_SCALE_WEIGHT_CURRENT = 5,
    FLOW_GLOBAL_VARIABLE_BREW_PROFILE = 6,
    FLOW_GLOBAL_VARIABLE_BREW_TEMP_TARGET = 7,
    FLOW_GLOBAL_VARIABLE_BREW_TIME_TARGET = 8,
    FLOW_GLOBAL_VARIABLE_BREW_WEIGHT_TARGET = 9,
    FLOW_GLOBAL_VARIABLE_BREW_VOLUMETRIC_DELETED = 10,
    FLOW_GLOBAL_VARIABLE_BREW_SHOW_ADJUSTMENT = 11,
    FLOW_GLOBAL_VARIABLE_STEAM_READY = 12,
    FLOW_GLOBAL_VARIABLE_STEAM_TEMP_TARGET = 13,
    FLOW_GLOBAL_VARIABLE_WATER_TEMP_TARGET = 14,
    FLOW_GLOBAL_VARIABLE_GRIND_WEIGHT_TARGET = 15,
    FLOW_GLOBAL_VARIABLE_GRIND_TIME_TARGET = 16,
    FLOW_GLOBAL_VARIABLE_PROFILE_SELECT_TOP_TEXT = 17,
    FLOW_GLOBAL_VARIABLE_SYSTEM = 18,
    FLOW_GLOBAL_VARIABLE_PROFILE = 19
};

// Native global variables

#ifdef __cplusplus
}
#endif

#endif /*EEZ_LVGL_UI_VARS_H*/