// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#include "../ui.h"

lv_obj_t *uic_BrewScreen_dials_tempTarget;
lv_obj_t *uic_BrewScreen_dials_tempGauge;
lv_obj_t *ui_BrewScreen = NULL;lv_obj_t *ui_BrewScreen_dials = NULL;lv_obj_t *ui_BrewScreen_ImgButton5 = NULL;lv_obj_t *ui_BrewScreen_contentPanel4 = NULL;lv_obj_t *ui_BrewScreen_targetTemp = NULL;lv_obj_t *ui_BrewScreen_saveButton = NULL;lv_obj_t *ui_BrewScreen_Image1 = NULL;lv_obj_t *ui_BrewScreen_standbyButton = NULL;lv_obj_t *ui_BrewScreen_lowerTemp = NULL;lv_obj_t *ui_BrewScreen_raiseTemp = NULL;
// event funtions
void ui_event_BrewScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP  ) {
lv_indev_wait_release(lv_indev_get_act());
      onStandby( e );
}
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      onBrewScreenLoad( e );
}
}

void ui_event_BrewScreen_ImgButton5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      onMenuClick( e );
}
}

void ui_event_BrewScreen_saveButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      onProfileSave( e );
}
}

void ui_event_BrewScreen_standbyButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      onStandby( e );
}
}

void ui_event_BrewScreen_lowerTemp( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      onBrewTempLower( e );
}
}

void ui_event_BrewScreen_raiseTemp( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      onBrewTempRaise( e );
}
}

// build funtions

void ui_BrewScreen_screen_init(void)
{
ui_BrewScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_BrewScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_add_event_cb(ui_BrewScreen, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, ui_BrewScreen_screen_destroy);
ui_object_set_themeable_style_property(ui_BrewScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Dark);
ui_object_set_themeable_style_property(ui_BrewScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Dark);
lv_obj_set_style_bg_img_src( ui_BrewScreen, &ui_img_pattern_art_deco_fixed_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_recolor(ui_BrewScreen, lv_color_hex(0x222222), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor_opa(ui_BrewScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BrewScreen_dials = ui_dials_create(ui_BrewScreen);
lv_obj_set_x( ui_BrewScreen_dials, 0 );
lv_obj_set_y( ui_BrewScreen_dials, 0 );

ui_BrewScreen_ImgButton5 = lv_imgbtn_create(ui_BrewScreen);
lv_imgbtn_set_src(ui_BrewScreen_ImgButton5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_2044104741, NULL);
lv_obj_set_width( ui_BrewScreen_ImgButton5, 40);
lv_obj_set_height( ui_BrewScreen_ImgButton5, 40);
lv_obj_set_x( ui_BrewScreen_ImgButton5, 0 );
lv_obj_set_y( ui_BrewScreen_ImgButton5, 210 );
lv_obj_set_align( ui_BrewScreen_ImgButton5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BrewScreen_ImgButton5, LV_OBJ_FLAG_HIDDEN );   /// Flags
ui_object_set_themeable_style_property(ui_BrewScreen_ImgButton5, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR, _ui_theme_color_NiceWhite);
ui_object_set_themeable_style_property(ui_BrewScreen_ImgButton5, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

ui_BrewScreen_contentPanel4 = lv_obj_create(ui_BrewScreen);
lv_obj_set_width( ui_BrewScreen_contentPanel4, 360);
lv_obj_set_height( ui_BrewScreen_contentPanel4, 360);
lv_obj_set_align( ui_BrewScreen_contentPanel4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_BrewScreen_contentPanel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BrewScreen_contentPanel4, 180, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BrewScreen_contentPanel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BrewScreen_contentPanel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_BrewScreen_contentPanel4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_NiceWhite);
ui_object_set_themeable_style_property(ui_BrewScreen_contentPanel4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_NiceWhite);
lv_obj_set_style_border_width(ui_BrewScreen_contentPanel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BrewScreen_targetTemp = lv_label_create(ui_BrewScreen_contentPanel4);
lv_obj_set_width( ui_BrewScreen_targetTemp, 180);
lv_obj_set_height( ui_BrewScreen_targetTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BrewScreen_targetTemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_BrewScreen_targetTemp,"92°C");
ui_object_set_themeable_style_property(ui_BrewScreen_targetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_NiceWhite);
ui_object_set_themeable_style_property(ui_BrewScreen_targetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_NiceWhite);
lv_obj_set_style_text_align(ui_BrewScreen_targetTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BrewScreen_targetTemp, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BrewScreen_saveButton = lv_imgbtn_create(ui_BrewScreen_contentPanel4);
lv_imgbtn_set_src(ui_BrewScreen_saveButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1594943393, NULL);
lv_obj_set_width( ui_BrewScreen_saveButton, 30);
lv_obj_set_height( ui_BrewScreen_saveButton, 30);
lv_obj_set_x( ui_BrewScreen_saveButton, 0 );
lv_obj_set_y( ui_BrewScreen_saveButton, 80 );
lv_obj_set_align( ui_BrewScreen_saveButton, LV_ALIGN_CENTER );
ui_object_set_themeable_style_property(ui_BrewScreen_saveButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR, _ui_theme_color_NiceWhite);
ui_object_set_themeable_style_property(ui_BrewScreen_saveButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

ui_BrewScreen_Image1 = lv_img_create(ui_BrewScreen);
lv_img_set_src(ui_BrewScreen_Image1, &ui_img_1951499226);
lv_obj_set_width( ui_BrewScreen_Image1, LV_SIZE_CONTENT);  /// 40
lv_obj_set_height( ui_BrewScreen_Image1, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( ui_BrewScreen_Image1, -1 );
lv_obj_set_y( ui_BrewScreen_Image1, -87 );
lv_obj_set_align( ui_BrewScreen_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BrewScreen_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BrewScreen_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_BrewScreen_Image1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR, _ui_theme_color_NiceWhite);
ui_object_set_themeable_style_property(ui_BrewScreen_Image1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

ui_BrewScreen_standbyButton = lv_imgbtn_create(ui_BrewScreen);
lv_imgbtn_set_src(ui_BrewScreen_standbyButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_coffee_sleep_60x60_png, NULL);
lv_obj_set_width( ui_BrewScreen_standbyButton, 60);
lv_obj_set_height( ui_BrewScreen_standbyButton, 60);
lv_obj_set_x( ui_BrewScreen_standbyButton, 0 );
lv_obj_set_y( ui_BrewScreen_standbyButton, 180 );
lv_obj_set_align( ui_BrewScreen_standbyButton, LV_ALIGN_CENTER );

ui_BrewScreen_lowerTemp = lv_imgbtn_create(ui_BrewScreen);
lv_imgbtn_set_src(ui_BrewScreen_lowerTemp, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_834125362, NULL);
lv_obj_set_width( ui_BrewScreen_lowerTemp, 40);
lv_obj_set_height( ui_BrewScreen_lowerTemp, 40);
lv_obj_set_x( ui_BrewScreen_lowerTemp, -120 );
lv_obj_set_y( ui_BrewScreen_lowerTemp, 0 );
lv_obj_set_align( ui_BrewScreen_lowerTemp, LV_ALIGN_CENTER );
ui_object_set_themeable_style_property(ui_BrewScreen_lowerTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR, _ui_theme_color_NiceWhite);
ui_object_set_themeable_style_property(ui_BrewScreen_lowerTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

ui_BrewScreen_raiseTemp = lv_imgbtn_create(ui_BrewScreen);
lv_imgbtn_set_src(ui_BrewScreen_raiseTemp, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_390988422, NULL);
lv_obj_set_width( ui_BrewScreen_raiseTemp, 40);
lv_obj_set_height( ui_BrewScreen_raiseTemp, 40);
lv_obj_set_x( ui_BrewScreen_raiseTemp, 120 );
lv_obj_set_y( ui_BrewScreen_raiseTemp, 0 );
lv_obj_set_align( ui_BrewScreen_raiseTemp, LV_ALIGN_CENTER );
ui_object_set_themeable_style_property(ui_BrewScreen_raiseTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR, _ui_theme_color_NiceWhite);
ui_object_set_themeable_style_property(ui_BrewScreen_raiseTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

lv_obj_add_event_cb(ui_BrewScreen_ImgButton5, ui_event_BrewScreen_ImgButton5, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BrewScreen_saveButton, ui_event_BrewScreen_saveButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BrewScreen_standbyButton, ui_event_BrewScreen_standbyButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BrewScreen_lowerTemp, ui_event_BrewScreen_lowerTemp, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BrewScreen_raiseTemp, ui_event_BrewScreen_raiseTemp, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BrewScreen, ui_event_BrewScreen, LV_EVENT_ALL, NULL);
uic_BrewScreen_dials_tempGauge = ui_comp_get_child(ui_BrewScreen_dials, UI_COMP_DIALS_TEMPGAUGE);
uic_BrewScreen_dials_tempTarget = ui_comp_get_child(ui_BrewScreen_dials, UI_COMP_DIALS_TEMPTARGET);

}

void ui_BrewScreen_screen_destroy(void)
{
   if (ui_BrewScreen) lv_obj_del(ui_BrewScreen);

// NULL screen variables
ui_BrewScreen= NULL;
ui_BrewScreen_dials= NULL;
uic_BrewScreen_dials_tempGauge= NULL;
uic_BrewScreen_dials_tempTarget= NULL;
ui_BrewScreen_ImgButton5= NULL;
ui_BrewScreen_contentPanel4= NULL;
ui_BrewScreen_targetTemp= NULL;
ui_BrewScreen_saveButton= NULL;
ui_BrewScreen_Image1= NULL;
ui_BrewScreen_standbyButton= NULL;
ui_BrewScreen_lowerTemp= NULL;
ui_BrewScreen_raiseTemp= NULL;

}
