// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#ifndef UI_BREWSCREEN_H
#define UI_BREWSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_BrewScreen
extern void ui_BrewScreen_screen_init(void);
extern void ui_BrewScreen_screen_destroy(void);
extern void ui_event_BrewScreen( lv_event_t * e);
extern lv_obj_t *ui_BrewScreen;
extern lv_obj_t *ui_BrewScreen_dials;
extern void ui_event_BrewScreen_ImgButton5( lv_event_t * e);
extern lv_obj_t *ui_BrewScreen_ImgButton5;
extern lv_obj_t *ui_BrewScreen_contentPanel4;
extern lv_obj_t *ui_BrewScreen_targetTemp;
extern void ui_event_BrewScreen_saveButton( lv_event_t * e);
extern lv_obj_t *ui_BrewScreen_saveButton;
extern lv_obj_t *ui_BrewScreen_Image1;
extern void ui_event_BrewScreen_standbyButton( lv_event_t * e);
extern lv_obj_t *ui_BrewScreen_standbyButton;
extern void ui_event_BrewScreen_lowerTemp( lv_event_t * e);
extern lv_obj_t *ui_BrewScreen_lowerTemp;
extern void ui_event_BrewScreen_raiseTemp( lv_event_t * e);
extern lv_obj_t *ui_BrewScreen_raiseTemp;
// CUSTOM VARIABLES
extern lv_obj_t *uic_BrewScreen_dials_tempGauge;
extern lv_obj_t *uic_BrewScreen_dials_tempTarget;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

