// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#include "../ui.h"

lv_obj_t *uic_StatusScreen_dials_tempTarget;
lv_obj_t *uic_StandbyScreen_dials_tempGauge;
lv_obj_t *ui_StandbyScreen = NULL;lv_obj_t *ui_StandbyScreen_dials = NULL;lv_obj_t *ui_StandbyScreen_Image12 = NULL;lv_obj_t *ui_StandbyScreen_Image13 = NULL;lv_obj_t *ui_StandbyScreen_targetTemp = NULL;
// event funtions
void ui_event_StandbyScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      onStatusScreenLoad( e );
}
if ( event_code == LV_EVENT_CLICKED) {
      onWakeup( e );
}
}

// build funtions

void ui_StandbyScreen_screen_init(void)
{
ui_StandbyScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_StandbyScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_add_event_cb(ui_StandbyScreen, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, ui_StandbyScreen_screen_destroy);
ui_object_set_themeable_style_property(ui_StandbyScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Dark);
ui_object_set_themeable_style_property(ui_StandbyScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Dark);
lv_obj_set_style_bg_img_src( ui_StandbyScreen, &ui_img_pattern_art_deco_fixed_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_recolor(ui_StandbyScreen, lv_color_hex(0x222222), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor_opa(ui_StandbyScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StandbyScreen_dials = ui_dials_create(ui_StandbyScreen);
lv_obj_set_x( ui_StandbyScreen_dials, 0 );
lv_obj_set_y( ui_StandbyScreen_dials, 0 );

ui_StandbyScreen_Image12 = lv_img_create(ui_StandbyScreen);
lv_img_set_src(ui_StandbyScreen_Image12, &ui_img_1732953241);
lv_obj_set_width( ui_StandbyScreen_Image12, LV_SIZE_CONTENT);  /// 60
lv_obj_set_height( ui_StandbyScreen_Image12, LV_SIZE_CONTENT);   /// 60
lv_obj_set_x( ui_StandbyScreen_Image12, 6 );
lv_obj_set_y( ui_StandbyScreen_Image12, 186 );
lv_obj_set_align( ui_StandbyScreen_Image12, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_StandbyScreen_Image12, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_StandbyScreen_Image12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_StandbyScreen_Image12, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_StandbyScreen_Image12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StandbyScreen_Image13 = lv_img_create(ui_StandbyScreen);
lv_img_set_src(ui_StandbyScreen_Image13, &ui_img_coffee_sleep_150x150_png);
lv_obj_set_width( ui_StandbyScreen_Image13, LV_SIZE_CONTENT);  /// 150
lv_obj_set_height( ui_StandbyScreen_Image13, LV_SIZE_CONTENT);   /// 150
lv_obj_set_align( ui_StandbyScreen_Image13, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_StandbyScreen_Image13, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_StandbyScreen_Image13, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_StandbyScreen_targetTemp = lv_label_create(ui_StandbyScreen);
lv_obj_set_width( ui_StandbyScreen_targetTemp, 120);
lv_obj_set_height( ui_StandbyScreen_targetTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_StandbyScreen_targetTemp, 4 );
lv_obj_set_y( ui_StandbyScreen_targetTemp, -140 );
lv_obj_set_align( ui_StandbyScreen_targetTemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_StandbyScreen_targetTemp,"60°C");
ui_object_set_themeable_style_property(ui_StandbyScreen_targetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_NiceWhite);
ui_object_set_themeable_style_property(ui_StandbyScreen_targetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_NiceWhite);
lv_obj_set_style_text_align(ui_StandbyScreen_targetTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_StandbyScreen_targetTemp, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_StandbyScreen, ui_event_StandbyScreen, LV_EVENT_ALL, NULL);
uic_StandbyScreen_dials_tempGauge = ui_comp_get_child(ui_StandbyScreen_dials, UI_COMP_DIALS_TEMPGAUGE);
uic_StatusScreen_dials_tempTarget = ui_comp_get_child(ui_StandbyScreen_dials, UI_COMP_DIALS_TEMPTARGET);

}

void ui_StandbyScreen_screen_destroy(void)
{
   if (ui_StandbyScreen) lv_obj_del(ui_StandbyScreen);

// NULL screen variables
ui_StandbyScreen= NULL;
ui_StandbyScreen_dials= NULL;
uic_StandbyScreen_dials_tempGauge= NULL;
uic_StatusScreen_dials_tempTarget= NULL;
ui_StandbyScreen_Image12= NULL;
ui_StandbyScreen_Image13= NULL;
ui_StandbyScreen_targetTemp= NULL;

}
