// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#include "../ui.h"

// COMPONENT dials

lv_obj_t *ui_dials_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_dials;
cui_dials = lv_obj_create(comp_parent);
lv_obj_remove_style_all(cui_dials);
lv_obj_set_width( cui_dials, 480);
lv_obj_set_height( cui_dials, 480);
lv_obj_set_align( cui_dials, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_dials, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t *cui_tempGauge;
cui_tempGauge = lv_arc_create(cui_dials);
lv_obj_set_width( cui_tempGauge, 480);
lv_obj_set_height( cui_tempGauge, 480);
lv_obj_set_align( cui_tempGauge, LV_ALIGN_CENTER );
lv_obj_add_state( cui_tempGauge, LV_STATE_DISABLED );     /// States
lv_arc_set_range(cui_tempGauge, 0,160);
lv_arc_set_value(cui_tempGauge, 80);
lv_arc_set_bg_angles(cui_tempGauge,118,62);
lv_obj_set_style_arc_width(cui_tempGauge, 35, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(cui_tempGauge, false, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_img_src( cui_tempGauge, &ui_img_untitled_png, LV_PART_MAIN | LV_STATE_DEFAULT );

lv_obj_set_style_arc_width(cui_tempGauge, 35, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(cui_tempGauge, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_img_src( cui_tempGauge, &ui_img_489054950, LV_PART_INDICATOR | LV_STATE_DEFAULT );

lv_obj_set_style_bg_color(cui_tempGauge, lv_color_hex(0xD10000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_tempGauge, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_tempTarget;
cui_tempTarget = lv_img_create(cui_dials);
lv_img_set_src(cui_tempTarget, &ui_img_340686386);
lv_obj_set_width( cui_tempTarget, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_tempTarget, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_tempTarget, -235 );
lv_obj_set_y( cui_tempTarget, -16 );
lv_obj_set_align( cui_tempTarget, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_tempTarget, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( cui_tempTarget, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(cui_tempTarget,-1760);
ui_object_set_themeable_style_property(cui_tempTarget, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR, _ui_theme_color_NiceWhite);
ui_object_set_themeable_style_property(cui_tempTarget, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

lv_obj_t *cui_tempIcon;
cui_tempIcon = lv_img_create(cui_dials);
lv_img_set_src(cui_tempIcon, &ui_img_1951499226);
lv_obj_set_width( cui_tempIcon, LV_SIZE_CONTENT);  /// 40
lv_obj_set_height( cui_tempIcon, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( cui_tempIcon, -85 );
lv_obj_set_y( cui_tempIcon, 200 );
lv_obj_set_align( cui_tempIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_tempIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( cui_tempIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(cui_tempIcon,150);
lv_obj_set_style_img_recolor(cui_tempIcon, lv_color_hex(0xF62C2C), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(cui_tempIcon, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_DIALS_NUM);
children[UI_COMP_DIALS_DIALS] = cui_dials;
children[UI_COMP_DIALS_TEMPGAUGE] = cui_tempGauge;
children[UI_COMP_DIALS_TEMPTARGET] = cui_tempTarget;
children[UI_COMP_DIALS_TEMPICON] = cui_tempIcon;
lv_obj_add_event_cb(cui_dials, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_dials, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_dials_create_hook(cui_dials);
return cui_dials; 
}

