// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#ifndef _UI_COMP_DIALS_H
#define _UI_COMP_DIALS_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT dials
#define UI_COMP_DIALS_DIALS 0
#define UI_COMP_DIALS_TEMPGAUGE 1
#define UI_COMP_DIALS_TEMPTARGET 2
#define UI_COMP_DIALS_TEMPICON 3
#define _UI_COMP_DIALS_NUM 4
lv_obj_t *ui_dials_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
